### ISSUE TITLE
Report A bug for netidx-wsproxy: A client's network error may block the netidx-wsproxy or make it very slow

### ISSUE THREAD

**Issue by MegaPikachu** [netidx/netidx#11] opened 2023-12-27 05:22 UTC
Hello, I find network error in a client may cause the netidx-wsproxy blocked or very slow. Could you help see what caused this bug and help fix it? Thanks.

The following steps is how I reproduced this bug:

(1) First I start the netidx-wsproxy in server A.
```
/path/to/netidx wsproxy --listen 0.0.0.0:8990
```

(2) Then I use the example "index.html" and "netidx-ws.js" to subscribe the same wsproxy and the same netidx path in two different computers B and C.
```
nx = new Netidx("ws://{ip of server A}:8990/ws");
nx.subscribe('/xxx/yyy/zzz', (v) => {
     console.log(v);
     return true
});
```
It works and I can console.log all the response from netidx in both these two computers B and C.

(3) I tried to simulate network issue by unplugging the network cable of computer C to make computer C disconnected.
At this moment, computer B start can not receive the latest netidx data from the wsproxy any more!!! This is very strange.
The proxy seems to can recover automatically, but the time is takes is extremely long, may over 10 minutes, which is unacceptable in a real-time running system.

**Comment by estokes** [comment] 2023-12-28 03:01
The JS was meant to be an example, I wouldn't use it for production on the JS side directly. You'd want to write your JS to ping/pong on the websocket fairly frequently so you can detect if the connection has died quickly. That would probably be quite easy to add to the example, if you want to take it on and send a PR I'd likely accept it.

**Comment by MegaPikachu** [comment] 2023-12-28 08:48
Thanks. I agree the JS is an example, it does not detect the connection. But the bug above is not caused by the JS. 
After I tested it more, I find it is caused by the rust code.

In line 258 of netidx-wsproxy/src/lib.rs
```
let (tx_up, mut rx_up) = mpsc::channel::<Pooled<Vec<(SubId, Event)>>>(3);
```
The size of this channel is only 3.
That causes this problem. I guess after one network error in a client, the server doesn't notice it immediately? Then this queue is filled with Events of clients that lost connection, which makes the total ws-proxy blocked.

After I changing this line with 
```
let (tx_up, mut rx_up) = mpsc::channel::<Pooled<Vec<(SubId, Event)>>>(1024 * 1024);
```
This problem can be solved.

If you agree with this, you can make the above change in the repo in your new version, thanks.

**Comment by MegaPikachu** [comment] 2023-12-28 09:37
I find I didn't set the timeout for the wsproxy. Maybe I can try to set timeout to see if it can solve the problem.

**Comment by base1172** [comment] 2023-12-28 09:59
This is a bit off topic, but perhaps the default netidx timeout should be more user friendly?  Casual users won't necessarily understand that the default "no timeout" means that a single slow client will cause their publisher to block sending updates to _EVERYONE_.

Would it be better to default to a reasonably small timeout (e.g., 5s), but allow users to explicitly set "no timeout" if they really don't want one?

@estokes I can prepare a PR if this proposal sounds okay.

**Comment by estokes** [comment] 2023-12-28 12:35
Yes, I agree for wsproxy.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by MegaPikachu** [comment] 2023-12-29 07:23
I agree to set a default timeout.It's another topic.

In this issue, I find setting the timeout as 1 second by
```
./netidx wsproxy --listen 0.0.0.0:8099 --timeout 1
```
 still can not solve the problem, the wsproxy is still blocked.
 
 Maybe increasing the buffer size can be a temporary fix, it doesn't solve the problem.
 If the buffer size is 1MiB and the proxy tries to send 1MiB of updates to a slow client, it will still block.

**Comment by estokes** [comment] 2023-12-30 22:32
so a couple of things. 

1. This is the slow consumer problem we're all so fond of in networking. I think the root cause is the timeout on the websocket is using the default tcp timeout, and it seems there is no way of changing this without changing warp. 
2. This isn't surprising, wsproxy was written so an electron app on the same machine could use netidx, it hasn't been tested in any other scenario (it's quite new).

I actually think a fix is pretty easy. At the moment, wsproxy shares a publisher and subscriber across all it's websocket clients. However a more correct mapping would be for each websocket client to have it's own publisher and it's own subscriber, this would allow different websocket clients on the same wsproxy to operate independently of each other, and would go a long way to fixing the issue.

To fully fix the issue, you should choose a correct timeout on the publisher side of your application. The way netidx deals with the slow consumer problem is for publishers to disconnect clients that can't consume updates fast enough. This allows netidx to have pushback, which is a very nice property to have.

I think this fix is small enough that you could probably do it yourself. I'd suggest providing an alternative entry point in wsproxy that uses a separate publisher/subscriber per websocket and leaving the default one as is, I know some commercial software is using it and it's optimal for their use case. If you feel up to it, send me a PR and I'll work with you. If not, I will put it on my (quite long list) of things to get to.

**Comment by base1172** [comment] 2023-12-30 23:02
> I'd suggest providing an alternative entry point in wsproxy that uses a separate publisher/subscriber per websocket and leaving the default one as is, I know some commercial software is using it and it's optimal for their use case. If you feel up to it, send me a PR and I'll work with you. If not, I will put it on my (quite long list) of things to get to.

Thanks...your suggestion is great. I think we can hack together something like that and deploy it internally next week.  Once we have some free cycles (probably a month from now), either @MegaPikachu or I can submit a more polished PR for you to review.

On a related note, we've been using an internal fork of the netidx Excel add-in (with write support added) for the last six months or so, and the ability to write to netidx containers from Excel has been great. At the moment our code to add write support is still quite messy, but we plan to submit a PR once it's been cleaned up.

**Comment by MegaPikachu** [comment] 2024-01-18 03:03
Thank you for your advice. We fully considered your suggestions, and tried making some fixes on the netidx-wsproxy.
We have submitted the PR here: https://github.com/netidx/netidx/pull/12

We think adding timeout for the reply function of the current websocket connection is the most simple way to fix this issue. It does solve the current problem without changing many codes. 

Currently the netidx-wsproxy creates many websocket connections, which share the same subscriber. With the new fix, if a network error occurs, the reply function wil reach the timeout, then the program close that websocket connection, so it won't affect the other clients.

And another change in this PR is: The parameter timeout can be set by user for netidx-wsproxy, but it is not used before. We use this timeout for both the timeout of the reply function, and the publisher's timeout in the netidx-wsproxy project.

**Comment by estokes** [comment] 2024-01-18 22:09
cool, I'll review it. Thank you for your contribution.

**Comment by estokes** [comment] 2024-02-03 20:13
Merged and released

**Closed by estokes** 2024-02-03 20:13 UTC
